import type { Metadata } from 'next';
import '../styles/globals.css';
import React from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <main className="flex items-center justify-center min-h-screen bg-gray-100 px-4 py-6 sm:px-6 box-border">
          {children}
        </main>
      </body>
    </html>
  );
}
